inherit_from:
  - .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
  RunRailsCops: true
